### ISSUE TITLE
Add Allata Treasure Valley

### ISSUE THREAD

**Issue by waded** [waded/gemstateio-groups#116]

**Comment by b-marie** [comment]
Weird timing that you just added this. I was just hoping to make a PR to get the new Allata group added, and found at least one other to add as well. Any chance you can add me as a contributor so that I can submit a PR?

**Comment by waded** [comment]
@b-marie Fork then submit PR if you'd like to make the change yourself! Thank you! If you don't have time, I'll resolve this issue myself (using the info from meetup.com) by Tuesday at the latest.

Would you mind submitting an issue w/ the other group(s) info, if nothing else? If you'd like to submit separate PRs to get those added too, that would be very helpful!

**Comment by b-marie** [comment]
Perfect, thanks! Submitted. Sorry I don't use GitHub all that often.

**Comment by waded** [comment]
Thanks @b-marie for adding the group info!
