### ISSUE TITLE
Track & resolve potential merger of two React groups

### ISSUE THREAD

**Issue by waded** [waded/gemstateio-groups#80]
Currently we have a listing for https://www.meetup.com/ReactJS-Boise/ but @brettadler mentioned a newer https://www.meetup.com/React-Meetup/ on Idaho Tech Slack, which I've added as well.

Find out if one or both are sticking around, and remove any group that has been deleted from groups.csv.

**Comment by waded** [comment]
Tagging @rdnewman who appears to be organizer of the original meetup I'd added to the listing in 2015.

**Comment by brettadler** [comment]
Just saw this. Lets talk Richard. Certainly no need for two groups, and we still haven't gotten ours going. So we can defer to yours if that's better....

**Comment by waded** [comment]
https://www.meetup.com/ReactJS-Boise/ has a meetup about Redux scheduled for Oct 22. I'm keeping both listed for now.

**Comment by brettadler** [comment]
@waded I can't speak for Richard's group, but we never did get our group kicked off. As of now there is no organizer for the group. So you may want to remove it from you list. Thanks!

**Comment by waded** [comment]
Thanks @brettadler. I removed the group from the list in my recent cleanup. Besides Richard's group, the Boise Front End Meetup often does sessions on React (maybe 30% of the sessions have something to do with it.)
